-- Conduit Phase 1 migration: conduit_jobs table
-- Generated by: forge conduit.gen.migrations
-- Run with:     forge depot migrate

CREATE TABLE conduit_jobs (
  id                TEXT        NOT NULL DEFAULT gen_random_uuid()::TEXT,
  queue             TEXT        NOT NULL DEFAULT 'default',
  job_type          TEXT        NOT NULL,
  payload           JSONB       NOT NULL DEFAULT '{}',
  status            TEXT        NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending','running','completed','failed','dead','snoozed')),
  attempt           INTEGER     NOT NULL DEFAULT 0,
  max_attempts      INTEGER     NOT NULL DEFAULT 3,
  priority          INTEGER     NOT NULL DEFAULT 0,
  backoff           TEXT        NOT NULL DEFAULT 'exponential',
  dead_letter_queue TEXT,
  inserted_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  scheduled_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  run_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at        TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ,
  heartbeat_at      TIMESTAMPTZ,
  worker_id         TEXT,
  errors            JSONB       NOT NULL DEFAULT '[]',
  tags              TEXT[]      NOT NULL DEFAULT '{}',
  meta              JSONB       NOT NULL DEFAULT '{}',
  PRIMARY KEY (id)
);

-- Primary poll index: queue + eligible statuses + ordering
CREATE INDEX idx_conduit_jobs_poll
  ON conduit_jobs (queue, status, priority DESC, run_at ASC)
  WHERE status IN ('pending', 'snoozed');

-- Status + time index for dashboard queries
CREATE INDEX idx_conduit_jobs_status
  ON conduit_jobs (status, inserted_at DESC);

-- LISTEN/NOTIFY: notify queue channel on each new job insert
CREATE OR REPLACE FUNCTION conduit_notify_new_job()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM pg_notify('conduit_queue_' || NEW.queue, NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER conduit_jobs_notify
  AFTER INSERT ON conduit_jobs
  FOR EACH ROW EXECUTE FUNCTION conduit_notify_new_job();
