-- Conduit Phase 2 migration: dead letters table + stale-job index
-- Generated by: forge conduit.gen.migrations
-- Run with:     forge depot migrate

CREATE TABLE conduit_dead_letters (
  id                 TEXT        NOT NULL DEFAULT gen_random_uuid()::TEXT,
  job_id             TEXT        NOT NULL,
  queue              TEXT        NOT NULL,
  job_type           TEXT        NOT NULL,
  payload            JSONB       NOT NULL,
  errors             JSONB       NOT NULL DEFAULT '[]',
  attempts           INTEGER     NOT NULL DEFAULT 0,
  first_attempted_at TIMESTAMPTZ,
  last_attempted_at  TIMESTAMPTZ,
  discarded_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed           BOOLEAN     NOT NULL DEFAULT FALSE,
  reviewed_by        TEXT,
  reviewed_at        TIMESTAMPTZ,
  retry_count        INTEGER     NOT NULL DEFAULT 0,
  meta               JSONB       NOT NULL DEFAULT '{}',
  PRIMARY KEY (id),
  UNIQUE (job_id)
);

-- Dashboard: list dead letters by queue, newest first
CREATE INDEX idx_conduit_dead_letters_queue
  ON conduit_dead_letters (queue, discarded_at DESC);

-- Dashboard: unreviewed dead letters
CREATE INDEX idx_conduit_dead_letters_unreviewed
  ON conduit_dead_letters (discarded_at DESC)
  WHERE reviewed = FALSE;

-- Stale-job detection: find running jobs with old heartbeats efficiently
CREATE INDEX idx_conduit_jobs_heartbeat
  ON conduit_jobs (heartbeat_at, status)
  WHERE status = 'running';
